<a href="https://colab.research.google.com/github/mrdbourke/tensorflow-deep-learning/blob/main/extras/solutions/%F0%9F%9B%A0%2000_TensorFlow_Fundamentals_%F0%9F%9B%A0_Exercises_%26_%F0%9F%93%96_Extra_curriculum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.6.0


# Exercise 

## 🛠 00 TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the **shape**, **rank** and **size** of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using **matrix multiplication**.
5. Multiply the two tensors you created in 3 using **dot product**.
6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.
7. Find the **min** and **max values** of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.
10. **One-hot** encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.


In [17]:
# Creating a scalar 
scalar = tf.constant([8])

# Creating a vector 
vector = tf.constant([1 , 2 , 3])

# Creating a matrix 
matrix = tf.constant([[1 ,2] , 
                      [3, 4]])

# Creating a tensor 
tensor = tf.constant([[10 , 9 , 8] , 
                      [1 ,2 , 4], 
                      [8 , 4 , 2]])

scalar , vector , matrix , tensor 

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10,  9,  8],
        [ 1,  2,  4],
        [ 8,  4,  2]], dtype=int32)>)

### 2. Find the **shape**, **rank** and **size** of the tensors you created in 1.

In [18]:
# Finding the shape, rank and size
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (3, 3)
The rank of the tensor: 9
The rank of the tensor: 2


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.


In [19]:
# Set seed
tf.random.set_seed(42)

# Setting up the shape 
tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5, 300))

tensor_1, tensor_1.shape, tensor_2, tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

### 4. Multiply the two tensors you created in 3 using **matrix multiplication**.


In [20]:
# Multiplying
print('Shape before the matrix multiplication')
print(tensor_1.shape , '\n')
print(tensor_2.shape , '\n')

resultant_vector = tf.linalg.matmul(tensor_1 , tf.transpose(tensor_2))
print(f'After multiplying the resultant vector is: {resultant_vector} \n')

print(f'The resultant vector shape: {resultant_vector.shape}')

Shape before the matrix multiplication
(5, 300) 

(5, 300) 

After multiplying the resultant vector is: [[80.333435 73.40498  77.15961  73.98368  80.90053 ]
 [75.14637  68.80438  74.24303  71.84184  75.60205 ]
 [79.7594   75.64456  77.79758  74.748726 80.55984 ]
 [75.085266 69.06408  74.30776  72.27615  76.05667 ]
 [85.05689  74.26629  78.00687  74.886795 83.13417 ]] 

The resultant vector shape: (5, 5)


### 5. Multiply the two tensors you created in 3 using **dot product**.


In [21]:
# Using tensordot
tf.tensordot(tensor_1 , tf.transpose(tensor_2) , axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

### 6. Create a tensor with **random values** between 0 and 1 with shape `[224, 224, 3]`.


In [22]:
# Tensor with shape [224 , 224 , 3]
big_tensor = tf.random.uniform(shape = [224 , 224 , 3], minval = 0 , maxval = 1)

big_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [23]:
# Checking the min and max value of our tensor 
print(f'Maximum value: {tf.reduce_max(big_tensor)}')
print(f'Minimum value: {tf.reduce_min(big_tensor)}')

Maximum value: 0.999991774559021
Minimum value: 2.384185791015625e-07


### 7. Find the **min** and **max values** of the tensor you created in 6.


In [24]:
# Finding the minimum 
minimum = tf.math.reduce_min(big_tensor)
print(f'The minimum value is: {minimum}')

The minimum value is: 2.384185791015625e-07


In [25]:
# Finding the maximum 
maximum = tf.math.reduce_max(big_tensor)
print(f'The maximum value is: {maximum}')

The maximum value is: 0.999991774559021


### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.


In [26]:
# Tensor with shape [224 , 224 , 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (1 , 224 , 224 , 3))

print(f'The shape before squeezing: {unsqueezed_tensor.shape}')

The shape before squeezing: (1, 224, 224, 3)


In [27]:
# And we are squeezing it 
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f'The shape after squeezing: {squeezed_tensor.shape}')

The shape after squeezing: (224, 224, 3)


### 9. Create a tensor with shape `[10]` using your own choice of values, then find the **index** which has the **maximum value**.


In [28]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])

# Finding the index where value is maximum 
max_value = tf.math.argmax(ten_tensor)

print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {ten_tensor[max_value]}')

The indices where the value is maximum: 6
The maximum value was: 10.0


### 10. **One-hot** encode the tensor you created in 9.

In [29]:
# Throw's an error since I had floating numbers in my tensor, casting to int solved! 
tf.cast(ten_tensor , dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  9, 10,  0,  0,  6], dtype=int32)>

In [30]:
# One hot encoding the tensor of shape 10 
tf.one_hot(tf.cast(ten_tensor , dtype=tf.int32) , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

## Extra Curriculum 

- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    - How would you calculate your grocery bill for the month and for the year using tensors?